# site settings
title: Clover Meadows Targhees
subtitle:
email: matthellwinkel@gmail.com
description:
baseurl:
url: http://clovermeadowsmt.org
author: mhellwinkel
street_address: 3424 Hwy 287
city: Sheridan
state: MT
zip_code: 59749
country: United States of America
phone: (406) 596-0668

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:

# build settings
markdown: kramdown

sass:
  style: compressed
