# site settings
title: Clover Meadows Targhees
subtitle:
email: matthellwinkel@gmail.com
description:
baseurl:
url: https://clovermeadows.github.io
author: mhellwinkel
street_address:
city: Sheridan
state: MT
zip_code: 59749
country: United States of America
phone: (406) 842-5235

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:

# build settings
markdown: kramdown

sass:
  style: compressed
